# Generated by Django 4.2.5 on 2023-09-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_page_shared_users_page_user_alter_page_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='shared_users',
        ),
    ]
