# Generated by Django 4.2.5 on 2023-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_alter_page_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
