# Generated by Django 4.2.5 on 2023-10-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_pagepermission_page_admin_list_remove_page_user_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='admin_list',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user_list',
        ),
        migrations.DeleteModel(
            name='PagePermission',
        ),
    ]
