# Generated by Django 4.2.5 on 2023-10-09 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitation', '0010_remove_page_admin_list_remove_page_user_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='admin_list',
            field=models.ManyToManyField(related_name='admin_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='user_list',
            field=models.ManyToManyField(related_name='accessed_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
